AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Central Authentication IAM resources'

Parameters:
  Environment:
    Type: String
    Default: "dev"
    AllowedValues: 
      - "dev"
      - "staging"
      - "prod"
    Description: The environment this template is being deployed to

  ServiceName:
    Type: String
    Description: Name for the central auth service
    Default: "AuthService"

  UserPoolId:
    Type: String
    Description: ID of the Cognito User Pool
    Default: ""

Resources:
  AuthServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ServiceName}-${Environment}-AuthRole'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
          - Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceName

  CognitoAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ServiceName}-${Environment}-CognitoPolicy'
      Roles:
        - !Ref AuthServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:AdminInitiateAuth
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminSetUserPassword
              - cognito-idp:AdminGetUser
              - cognito-idp:AdminUpdateUserAttributes
              - cognito-idp:AdminConfirmSignUp
              - cognito-idp:AdminRespondToAuthChallenge
              - cognito-idp:AdminAddUserToGroup
              - cognito-idp:AdminRemoveUserFromGroup
              - cognito-idp:AdminListGroupsForUser
              - cognito-idp:GetUser
              - cognito-idp:UpdateUserAttributes
              - cognito-idp:ChangePassword
              - cognito-idp:ForgotPassword
              - cognito-idp:ConfirmForgotPassword
              - cognito-idp:InitiateAuth
              - cognito-idp:RespondToAuthChallenge
              - cognito-idp:ListUsers
              - cognito-idp:ListGroups
              - cognito-idp:ListUsersInGroup
            Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'

  CrossAccountCognitoAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ServiceName}-${Environment}-CrossAccountCognitoPolicy'
      Roles:
        - !Ref AuthServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ServiceName}-${Environment}-ClientRole'

  ParameterStoreAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ServiceName}-${Environment}-ParameterStorePolicy'
      Roles:
        - !Ref AuthServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/${Environment}/*'
            
  SecretsManagerAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ServiceName}-${Environment}-SecretsManagerPolicy'
      Roles:
        - !Ref AuthServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ServiceName}/${Environment}/*'

  ClientApplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ServiceName}-${Environment}-ClientRole'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceName

  ClientCognitoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ServiceName}-${Environment}-ClientCognitoPolicy'
      Roles:
        - !Ref ClientApplicationRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:InitiateAuth
              - cognito-idp:RespondToAuthChallenge
              - cognito-idp:GetUser
            Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'

Outputs:
  AuthServiceRoleArn:
    Description: ARN of the Central Auth IAM Role
    Value: !GetAtt AuthServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AuthServiceRoleArn'

  AuthServiceRoleName:
    Description: Name of the Central Auth IAM Role
    Value: !Ref AuthServiceRole
    Export:
      Name: !Sub '${AWS::StackName}-AuthServiceRoleName'
      
  ClientApplicationRoleArn:
    Description: ARN of the Client Application IAM Role
    Value: !GetAtt ClientApplicationRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ClientApplicationRoleArn'
      
  ClientApplicationRoleName:
    Description: Name of the Client Application IAM Role
    Value: !Ref ClientApplicationRole
    Export:
      Name: !Sub '${AWS::StackName}-ClientApplicationRoleName'